### ISSUE TITLE
estimate gas for a transaction 

### ISSUE THREAD

**Issue by JohnGuilding** [getwax/bls-wallet#410]
**As a** third party wallet,
**I would like** to know how much gas fee I should charge the user for a transaction in advance 
**So that** I can easily estimate the tx cost and/or collect the gas fee from the user and pay through one of my own addresses.

### Recommendation
- Add an `/estimateFee` endpoint to the aggregator and also implement `estimateGas` method on the Signer such that it works exactly the same as the usual RPC call

**Comment by voltrevo** [comment]
@JohnGuilding @kautukkundan We've had `/estimateFee` on the aggregator since March last year #161 (much older than this issue). Is some clarification needed here?

**Comment by kautukkundan** [comment]
@voltrevo yeah, also John already added the endpoint in the provider. Just need to add tests and see if things work as expected and if there needs to match to any spec (currently the estimateFee is called as estimateGas in the provider)

**Comment by voltrevo** [comment]
@kautukkundan

When you say 'yeah', is it:
- 'yeah I know' or
- 'yeah some clarification is needed'?

I *think* it's the former... 😅

**Comment by voltrevo** [comment]
Hmm ChatGPT thinks I didn't need to reply 😂

![Screen Shot 2023-02-01 at 3 21 33 pm](https://user-images.githubusercontent.com/9291586/215946165-5af6cbf5-d04e-45b5-9725-6db655ebffae.png)

**Comment by kautukkundan** [comment]
😂 that's one brand new use-case for chatGPT
