### ISSUE TITLE
Try to use hubble-bls directly instead of using copy

### ISSUE THREAD

**Issue by voltrevo** [getwax/bls-wallet#9]

**Comment by voltrevo** [comment]
Revisited this again today, ran into an issue with @thehubbleproject/bls+esm.sh described here:
https://github.com/alephjs/esm.sh/issues/193

I've submitted a PR to @thehubbleproject/bls to add `src/index.ts` which may resolve the issue:
https://github.com/thehubbleproject/hubble-bls/pull/19

I think this shouldn't be a priority, and we should revisit it only if it becomes convenient or there are hubblebls changes that we need to bring in.

**Comment by jacque006** [comment]
Resolved in https://github.com/jzaki/bls-wallet/pull/92
